### ISSUE TITLE
Windows conda build

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#181]
Hopefully we can get this working for non-developers wanting to install on Windows.
We should also update the windows installation documentation.

Ron is working on this.

**Comment by barkls** [comment]
@ralexander

**Comment by barkls** [comment]
@ralex0

**Comment by ralex0** [comment]
I was able to successfully build and install a holopy Anaconda package (preferred built distribution format as suggested by @vnmanoharan) on my win-64 python 3.6 environment.

But I suppose I should wait until all the other issue on the milestone have been closed before doing the official build, right?

**Comment by vnmanoharan** [comment]
We should test it before the final release, to make sure it works on other (Windows) machines.  Not sure if GitHub has a mechanism for doing this, so you might want to email it to me and @barkls to test.

**Comment by jeromefung** [comment]
Hi Ron --

Out of curiosity, what ended up being the solution to the issue with the
scipy.special spherical Bessel functions we were running into yesterday?

Best,
Jerome

**Comment by barkls** [comment]
fyi conda-forge uses a continuous integration platform called appveyor to test Windows builds. 

I don't know how easy it is to set up, or if it is even free, so I agree the best option is to send it to me and Vinny. 

Jerome: I'm not certain what the final resolution was, so I defer to @tdimiduk

**Comment by ralex0** [comment]
I'm not allowed to upload the file to gmail because it's executable code, but zipping it and uploading here works.

[holopy-3.0-0.tar.zip](https://github.com/manoharan-lab/holopy/files/1072794/holopy-3.0-0.tar.zip)

I believe all you have to do is drop this in `~\Anaconda3\conda-bld` or equivalent, then do `conda install --use-local holopy`

**Comment by ralex0** [comment]
@jeromefung I think building scipy yourself from the source might fix it, but I have not confirmed. 

If you recall, our issue is a duplicate of scipy/scipy#7002 and it seems they determined that it's a problem with Anaconda's scipy build. The open issue is ContinuumIO/anaconda-issues#1415.

I think for now we decided to skip that test for Windows users. @tdimiduk suggested using `nose.SkipTest`, but I didn't get that working properly yet. This is one of the commits I wanted to make before the final build.

**Comment by vnmanoharan** [comment]
I was able to install it on Windows 10 build 15063 by unzipping first, then installing with "conda install holopy-3.0.0.tar.bz2".  But after running `import holopy` from python, I get the following error:
```
UserWarning:
Could not import scattering.  You will not be able to do scattering
calculations, but the rest of holopy should remain usable.
This is probably due to a problem with compiling fortran code
```
@ralex0, could you verify that the scattering module imports correctly for you, and that you are able to do scattering calculations?  If so I will try to debug the error.

**Comment by ralex0** [comment]
I got the same warning, so I want to investigate as well. I also got this warning when I install from a Windows (.exe) built distribution, but in that case, the scattering code worked in the sense that 

1. I could run all the code from the scattering tutorial (maybe @charlieGreboval can confirm as he installed from an exe) and
2. Almost all of the nosetests pass. One of the exceptions is the test that @jeromefung was referring to earlier in this thread.

With this Anconda build, I can't actually do `from holopy import scattering` as I could with the previous .exe builds. I will update if I get a clue on what's going on here.

**Comment by barkls** [comment]
Try running ``from holopy.scattering import Mie``. If that works, then the scattering code should be correctly compiled. 

I can help with a skiptest if you can't get it working.

**Comment by vnmanoharan** [comment]
Here is some more info. The problem seems to lie in loading any of the .pyd extensions generated by the fortran compiler.  If I run `from holopy.scattering.theory import mie`, for example, I get 
```
ImportError                               Traceback (most recent call last)
<ipython-input-7-486223fbfc57> in <module>()
----> 1 from holopy.scattering.theory import mie

~\Anaconda3\lib\site-packages\holopy\scattering\theory\mie.py in <module>()
     32 from ..scatterer import Sphere, Scatterers
     33 from .scatteringtheory import ScatteringTheory
---> 34 from .mie_f import mieangfuncs, miescatlib
     35 from .mie_f.multilayer_sphere_lib import scatcoeffs_multi
     36

~\Anaconda3\lib\site-packages\holopy\scattering\theory\mie_f\mieangfuncs.cp36-win_amd64.pyd in <module>()

~\Anaconda3\lib\site-packages\holopy\scattering\theory\mie_f\mieangfuncs.cp36-win_amd64.pyd in __bootstrap__()

~\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    340         spec = importlib.machinery.ModuleSpec(
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343
    344 else:

ImportError: DLL load failed: The specified module could not be found.
```
So I am missing a library (DLL) required for the module to load.  I opened up a shell and ran `dumpbin /dependents mieangfuncs.cp36-win_amd64.pyd` (dumpbin is a Visual C utility), which told me:

```Dump of file mieangfuncs.cp36-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    python36.dll
    libifcoremd.dll
    libmmd.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
```
So one of these DLLs probably has to be installed on Windows to be able to run the module.  But I don't yet have a way to figure out which one is missing.

**Comment by vnmanoharan** [comment]
Update: it looks like `libifcoremd.dll` and `libmmd.dll` are the missing DLLs.  These are DLLs that the Intel fortran compiler links to. @ralex0, which version of the Intel compiler did you use?  They have links to DLL files that can be downloaded by end-users of Intel-compiled applications, but I am not sure which link to choose.

**Comment by ralex0** [comment]
@barkls:
Something went wrong I suppose. I don't really know how to use SkipTest, so if it's a 2 min thing for you to do, you can edit the file. The test I was referring to is `test_dda.py:test_dda__2_cpu`. I think all is needs is a `if os.name == 'nt'`...

For the curious, here's what happens:
```python
In [1]: from holopy.scattering import Mie
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
C:\Users\Ron\Anaconda3\lib\site-packages\holopy\scattering\theory\__init__.py:42: UserWarning:
Could not import scattering.  You will not be able to do scattering
calculations, but the rest of holopy should remain usable.
This is probably due to a problem with compiling fortran code
  This is probably due to a problem with compiling fortran code""")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-853bce84552e> in <module>()
----> 1 from holopy.scattering import Mie

ImportError: cannot import name 'Mie'
```

I just checked and 'm on numpy 1.11.3 (11=b I surmise). IIRC holopy requires numpy>1.12 so I think that might be my problem here.

**Comment by ralex0** [comment]
Maybe looking into this numpy thing will fix Vinny's problem too but:
@vnmanoharan:
I have installed Intel Parallel Studio 2017 to get the Intel Fortran compiler (ifort). The specific version of ifort is Version 17.0.2.187 Build 20170213. If the libraries they have on their website work, maybe we can include them in a holopy/dist directory.

**Comment by barkls** [comment]
numpy >= 1.12 is required for Multisphere calculations, but Mie should work fine on numpy 1.11.

**Comment by ralex0** [comment]
@barkls For curiosity and posterity, do you happen to know what specifically changed between numpy 1.11 and numpy 1.12 that make the Multisphere calculations possible? Is this mentioned anywhere?

**Comment by barkls** [comment]
I don't know. I think it has to do with the xarray upgrade to 9.0 but I'm not 100% sure on that. I didn't spend too much time tracking down the specific cause since it works on 1.12.

**Comment by vnmanoharan** [comment]
@ralex0, can you try to generate a conda package that is statically linked to the intel fortran libraries?  That will probably be the easiest option for redistribution.  There should be a compiler switch you can use to enable static linking.

**Comment by ralex0** [comment]
@vnmanoharan [Try this one.](https://github.com/manoharan-lab/holopy/files/1075253/holopy-3.0-0_testbuild.tar.zip) I installed from it, and I did not get any Fortran warnings this time. Additionally `from holopy.scattering import Mie` works.

**Comment by vnmanoharan** [comment]
I get the same error, `ImportError: DLL load failed: The specified module could not be found.`.  Likely it works on your computer because you have the Intel libraries installed already. I do not, so I either have to install them myself or use a statically-linked version of the package.  It will be much easier to distribute if the libraries are statically linked.  Can you try building a package with statically linked libraries?

**Comment by ralex0** [comment]
Okay I'll try some more. I though I had set it to statically link, but I think something went wrong.

**Comment by vnmanoharan** [comment]
@ralex0: any updates?

**Comment by ralex0** [comment]
I haven't gotten those Intel libraries to be statically linked in yet. It seems like ifort ignores the options I pass because when I examine the pyd files in  `holopy/scattering/theory/mie_f` it shows dependencies on those Intel libraries. It has led me to think the compiler/linker options are being overwritten by something else. If I recall, the only thing that takes precedence over local variables is options passed explicit in the call to the program.

The questions I have asked myself are how exactly is the Fortran compiled and what line actually calls the compiler? I was looking at `holopy/scattering/theory/mie_f/setup.py`, and it looks like that uses __numpy.distutils__. I investigated `numpy/distutils/fcompile/intel.py` it looks like the f compiler is always invoked with a -shared flag: perhaps this desirable if you're using gfortran.

Here is a snippet: 

```python
class BaseIntelFCompiler(FCompiler):
    def update_executables(self):
        f = dummy_fortran_file()
        self.executables['version_cmd'] = ['<F77>', '-FI', '-V', '-c',
                                           f + '.f', '-o', f + '.o']

    def runtime_library_dir_option(self, dir):
        return '-Wl,-rpath="%s"' % dir


class IntelEM64TFCompiler(IntelFCompiler):
    compiler_type = 'intelem'
    compiler_aliases = ()
    description = 'Intel Fortran Compiler for 64-bit apps'

    version_match = intel_version_match('EM64T-based|Intel\\(R\\) 64|64|IA-64|64-bit')

    possible_executables = ['ifort', 'efort', 'efc']

    executables = {
        'version_cmd'  : None,
        'compiler_f77' : [None, "-FI"],
        'compiler_fix' : [None, "-FI"],
        'compiler_f90' : [None],
        'linker_so'    : ['<F90>', "-shared"],
        'archiver'     : ["ar", "-cr"],
        'ranlib'       : ["ranlib"]
        }

    def get_flags(self):
        return ['-fPIC']

    def get_flags_opt(self):  # Scipy test failures with -O2
        v = self.get_version()
        mpopt = 'openmp' if v and int(v.split('.')[0]) < 15 else 'qopenmp'
        return ['-fp-model strict -O1 -{}'.format(mpopt)]

    def get_flags_arch(self):
        return ['']
```

I tried hacking numpy by changing all instances of "-shared" to "-static" (I am not sure if the choice to pass "-shared" to the linker is a bug or a feature) and using that to build my distribution, but it still ends up using shared libraries, so that didn't solve it. Maybe there is something other way I can change it. I haven't looked up what "linker_so" stands for. "Linker shared object", I guess.

I also noticed conda makes copies of the shared libraries its packages need in `Anaconda3\Library\bin` so I'm trying to figure out if maybe conda is betraying me somehow by always preferring to use the shared libraries. I don't think so, but maybe.

The other possibly is these libraries cannot be statically linked. 

If anyone has any insight it would be appreciated.

**Comment by vnmanoharan** [comment]
@ralex0: It looks like the option to pass is `-static-intel` (see https://stackoverflow.com/questions/33781867/compile-and-link-fortran-and-c-with-ifort-and-icc).  That should statically link the intel libraries and dynamically link everything else.

Interestingly, I also found out that in Anaconda3\Library\bin I already have copies of libmmd.dll and libifcoremd.dll (probably installed with numpy/scipy).  When python starts, this directory is automatically added to the search path.  So it might be that Python *is* finding the libraries, but that they are a different version than what is expected.  It could be very bad to overwrite the libraries in this directory, if they are being used by other packages.  So I think the only solution is static linking.

**Comment by ralex0** [comment]
@vnmanoharan 
Interesting that you have the DLLs. I wonder if the linker knows to look there? When I check the built pyd/dll files for dependencies, it always points to the DLLs I have stored under `"Program Files (x86)\IntelSWTools"` even though the Anaconda bin directory comes first in my PATH. You're probably right about it being the wrong version. I suppose we could also include libraries in a `dist/` directory, but static linking is a better solution than potentially starting a [DLL Hell](https://en.wikipedia.org/wiki/DLL_Hell) scenario.

Most things I've found on the internet appear to be outdated or are instructions for Linux/OSX. I've tried the flags are `-static` or `-static-intel` but I noticed these options don't even appear when you invoke the help document. I think the advice given there is for Linux users since windows doesn't use .a shared libraries, it uses .dll along with .lib which I am beginning to understand work in a completely different manner than shared library formats on other platforms.

I now think the option is `/link /libs:static` based on `ifort /help`.  Today, I'm trying it  all the ways I have already tried passing  `static`, `/static`, `/static-intel`, etc.

I'm attaching the help doc here because this is probably the version of ifort we will end up building with, and I haven't seen this on the net anywhere.

[ifort_help_V7.0.2.187_B20170213.txt](https://github.com/manoharan-lab/holopy/files/1091515/ifort_help_V7.0.2.187_B20170213.txt)

**Comment by vnmanoharan** [comment]
It looks like you might also have to specify the switch `/MT`, and you might also have to specify the statically-linkable version of the library, which is `libifcoremt.lib` (note the `mt` on the end instead of `md`) and `libmmt.lib` on the command line; see http://csbi.mit.edu/technology/intel_fce/doc/main_for/mergedProjects/bldaps_for/common/bldaps_compile_mthread.htm.  The `/MD` switch is now default, which links to DLLs.  Using `/MT` will link to static libraries.

**Comment by ralex0** [comment]
@vnmanoharan @barkls 
How about this build?
[holopy-3.0-1.tar.bz2.zip](https://github.com/manoharan-lab/holopy/files/1092621/holopy-3.0-1.tar.bz2.zip)

**Comment by barkls** [comment]
Same error. Sorry.

**Comment by vnmanoharan** [comment]
@ralex: same error here too, but the package does seem to be statically linked to the intel libraries now.  I'm going through with [Dependency Walker](http://www.dependencywalker.com/) to see if I can get more information on what's going wrong with the DLL load.

**Comment by ralex0** [comment]
I have installed that build on an entirely different Windows 10 64-bit installation. I didn't get any import errors, what DLLs does it say that you are missing?

**Comment by vnmanoharan** [comment]
Apparently the problem is that I'm on Python 3.5, and the package was compiled with Python 3.6.  `dumpbin /dependents mieangfuncs.cp36-win_amd64.pyd` shows the following:

```
File Type: DLL

  Image has the following dependencies:

    python36.dll
    KERNEL32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    imagehlp.dll
```
I'll update to 3.6 and see if it works.

**Comment by vnmanoharan** [comment]
I upgraded to Python 3.6, and I now get the following error:
```
In [1]: import holopy
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
```
@ralex0, how did you solve your numpy problems?  I am running numpy 1.12.1.

**Comment by ralex0** [comment]
@vnmanoharan 
Upgrade to numpy 1.13 and then try to import.

**Comment by ralex0** [comment]
You can install my latest build with `conda install -c ralex0 holopy`
It requires numpy 1.13, but I have disabled the version check beacause a lot of the default packages in Anaconda require numpy 1.12 and it is not trivial to resolve dependencies.

**Comment by vnmanoharan** [comment]
Thanks - still trying to get upgraded to numpy 1.13 (keep getting "UnsatisfiableError" from conda).  I was able to install holopy from your channel.  A couple of notes:

- had to install `h5cdfnet` from conda-forge. There is no version that works on windows in the main conda channel
- had to install `pyyaml` and `yaml` from conda-forge. I had these installed from the main channel, but `import yaml` gave an error, for some reason.

**Comment by vnmanoharan** [comment]
@ralex0, can you send me a spec file or environment.yml file so that I can reproduce your environment?
https://conda.io/docs/using/envs.html#share-an-environment

**Comment by ralex0** [comment]
`pip install numpy=1.13` didn't break anything for me (that I can see so far) that's how I got numpy installed.

I have encountered both those things. I suppose the full instructions are first run `conda config --add channels conda-forge` then run `conda install -c ralex0 holopy`.

It seems to me that yaml package on the default channel is a dll, whereas on conda-forge it is a subpackage of the pyyaml package. That's a bit annoying.

[Here is my build environment.](https://github.com/manoharan-lab/holopy/files/1132226/ron-holopy-build-win64.zip)

**Comment by ralex0** [comment]
[Here is the environment](https://github.com/manoharan-lab/holopy/files/1132268/ron-holopy-run-win64.zip) of a computer where I have it running, but don't have the intel compiler installed.

**Comment by vnmanoharan** [comment]
Does it compile against numpy 1.12?

**Comment by ralex0** [comment]
It's technically 1.13. I forked numpy and patched it to enable static linking while building Fortran extensions. In numpy.distutils they hard-coded a compiler switch that automatically uses the shared libraries rather than the static ones. See https://github.com/ralex0/numpy/commit/036df88f8524bf67b3dca4ae744b734316861c5b

**Comment by vnmanoharan** [comment]
I think (despite what I said earlier) that static linking might not be necessary. It looks like libifcoremd.dll and libmmd.dll are both installed with numpy/scipy.  So if the same version of the intel fortran compiler is used to compile holopy as numpy/scipy, dynamic linking might be fine.  I think my previous problem was python 3.5 vs 3.6.

**Comment by vnmanoharan** [comment]
It works! I installed your build environment, @ralex0, though I had to delete conda and conda-env, since those are only allowed in the root environment. I also had to remove the numba package, since it doesn't yet work with numpy 1.13 -- see [here](https://github.com/numba/numba/issues/2412). Then I was able to install numpy 1.13 using `conda install numpy=1.13`. Finally, I was able to get holopy and the scattering modules working.

Numpy 1.13 should soon be the default for anaconda, so I don't think we need to compile against numpy 1.12. But I would like to see if a dynamically linked package will work. Can you go back to the previous configuration and generate a version of holopy with dynamic linking to the fortran libraries?  I'll see if that works on my end.

**Comment by ralex0** [comment]
@vnmanoharan 
`conda install -c ralex0 holopy=v3.0post1`

**Comment by vnmanoharan** [comment]
That works too, and the dynamic dependencies seem to be all pulled in. @barkls, can you confirm that Ron's dynamically linked build works for you? You will need to upgrade to python 3.6 and numpy 1.13.  Once confirmed that it works on your machine, we can mark this issue as closed.

**Comment by barkls** [comment]
It works for me as well. I'll update the docs to reflect the new installation procedure.
